{{- if .Values.server.cpuAutoscaling.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "trino.worker" . }}
  {{- if .Values.commonLabels }}
  labels:
    {{- tpl (toYaml .Values.commonLabels) . | nindent 4 }}
  {{- end }}
spec:
  maxReplicas: {{ .Values.server.cpuAutoscaling.maxReplicas }}
  minReplicas: {{ .Values.server.workers }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "trino.worker" . }}
  targetCPUUtilizationPercentage: {{ .Values.server.cpuAutoscaling.targetCPUUtilizationPercentage }}
{{- end }}
